FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install global dependencies
RUN npm install -g react-scripts

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy frontend source files
COPY src ./src
COPY public ./public
COPY .env ./
COPY src/setupProxy.js ./

# Expose frontend port
EXPOSE 3000

# Start frontend development server
CMD ["npm", "start"]
